version: 2.1

executors:
  windows:
    machine:
      enabled: true
      resource_class: windows.large
    shell: powershell.exe

jobs:
  worker:
    parameters:
      job_id:
        type: integer
    executor: windows
    steps:
      - checkout

      - run:
          name: Generate log for job << parameters.job_id >>
          command: |
            New-Item -ItemType Directory -Force -Path logs | Out-Null
            "=== Job << parameters.job_id >> ===" | Out-File -Encoding utf8 logs\log-<< parameters.job_id >>.txt
            "Working on job << parameters.job_id >> ..." | Out-File -Encoding utf8 -Append logs\log-<< parameters.job_id >>.txt
            Start-Sleep -Seconds (Get-Random -Minimum 1 -Maximum 6)
            "Done with job << parameters.job_id >>" | Out-File -Encoding utf8 -Append logs\log-<< parameters.job_id >>.txt
            java -jar tf12.jar

      - persist_to_workspace:
          root: logs
          paths:
            - log-<< parameters.job_id >>.txt

  merge_logs:
    executor: windows
    steps:
      - attach_workspace:
          at: workspace

      - run:
          name: Merge all logs
          command: |
            New-Item -ItemType Directory -Force -Path merged | Out-Null
            Get-ChildItem -Path workspace\log-*.txt | Sort-Object Name | ForEach-Object {
              Get-Content $_.FullName
            } | Out-File -Encoding utf8 merged\all-logs.txt

            Write-Host "===== MERGED LOGS (first 100 lines) ====="
            Get-Content merged\all-logs.txt | Select-Object -First 100
            Write-Host "===== END PREVIEW ====="

      - store_artifacts:
          path: merged\all-logs.txt
          destination: all-logs.txt

workflows:
  version: 2
  parallel-30-windows:
    jobs:
      # 30 workers on Windows
      - worker:
          name: worker-1
          job_id: 1
      - worker:
          name: worker-2
          job_id: 2
      - worker:
          name: worker-3
          job_id: 3
      - worker:
          name: worker-4
          job_id: 4
      - worker:
          name: worker-5
          job_id: 5
      - worker:
          name: worker-6
          job_id: 6
      - worker:
          name: worker-7
          job_id: 7
      - worker:
          name: worker-8
          job_id: 8
      - worker:
          name: worker-9
          job_id: 9
      - worker:
          name: worker-10
          job_id: 10
      - worker:
          name: worker-11
          job_id: 11
      - worker:
          name: worker-12
          job_id: 12
      - worker:
          name: worker-13
          job_id: 13
      - worker:
          name: worker-14
          job_id: 14
      - worker:
          name: worker-15
          job_id: 15
      - worker:
          name: worker-16
          job_id: 16
      - worker:
          name: worker-17
          job_id: 17
      - worker:
          name: worker-18
          job_id: 18
      - worker:
          name: worker-19
          job_id: 19
      - worker:
          name: worker-20
          job_id: 20
      - worker:
          name: worker-21
          job_id: 21
      - worker:
          name: worker-22
          job_id: 22
      - worker:
          name: worker-23
          job_id: 23
      - worker:
          name: worker-24
          job_id: 24
      - worker:
          name: worker-25
          job_id: 25
      - worker:
          name: worker-26
          job_id: 26
      - worker:
          name: worker-27
          job_id: 27
      - worker:
          name: worker-28
          job_id: 28
      - worker:
          name: worker-29
          job_id: 29
      - worker:
          name: worker-30
          job_id: 30

      - merge_logs:
          requires:
            - worker-1
            - worker-2
            - worker-3
            - worker-4
            - worker-5
            - worker-6
            - worker-7
            - worker-8
            - worker-9
            - worker-10
            - worker-11
            - worker-12
            - worker-13
            - worker-14
            - worker-15
            - worker-16
            - worker-17
            - worker-18
            - worker-19
            - worker-20
            - worker-21
            - worker-22
            - worker-23
            - worker-24
            - worker-25
            - worker-26
            - worker-27
            - worker-28
            - worker-29
            - worker-30
